# Generated by Django 4.1.5 on 2023-01-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiValuedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('data_source', models.CharField(max_length=30)),
                ('data_type', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user_id', 'data_source', 'data_type')},
            },
        ),
    ]
